### ISSUE TITLE
[FEATURE] Add a global way to work with comeback

### ISSUE THREAD

**Issue by agamm** [agamm/comeback#17]
So we are lazy, right? (I literally just ignored the issue template, you see?)
Anyhow, how cool would it be to be able to call comeback not only from within the directory of a project? But from everywhere!   
It will remember all of the previous projects and ask you which one to run.

So it will look something like this:
1) Open terminal
2) type comeback
-- mind you we aren't in a .comeback filled directory
3) comeback will realize it doesn't have a .comeback file in the current dir, so it will ask the user which one to use from the previous runs (it will save them)
Like this:
```
comeback
Hmm... No .comeback file found. do you want to start one of these?
1) path to project 0
2) path to project 1
3) path to project 2
```
N2H: Autocomplete results
N2H: write last time opened and sort that way
N2H: add ability to choose project with up and down arrows and enter.

**Comment by yammesicka** [comment]
What about automagically running the default recipe? No questions asked might be better option for sloths :P

We can allow the user to do `comeback --list` to open all the possibilities.

**Comment by agamm** [comment]
@yammesicka I think that if comeback is in a directory that already has a .comeback recipe then it should run it first. Only when it doesn't find it should open the last used one (default) and --list can work until we have autocomplete.

**Comment by agamm** [comment]
Also, after this is done then I think we will be able to add a gif showcasing how this works.

**Comment by agamm** [comment]
https://github.com/Mckinsey666/bullet
